name: tropkcab
description: Backport PRs with just a label
author: Ewan Harris
inputs:
  username:
    required: true
    description: Username of the account that will create PRs and host the git repo
  github_token:
    required: true
    description: Token to use for the GitHub API, you most likely want to pass through secrets.GITHUB_TOKEN
runs:
  using: node12
  main: dist/index.js
